---
# tasks file for atom - EL Family

- name: EL Family | Adding repository {{ atom_repo_el }}
  ansible.builtin.yum_repository:
    name: "{{ atom_repo_el_name }}"
    description: "{{ atom_repo_el_description }}"
    baseurl: "{{ atom_repo_el }}"
    gpgcheck: "{{ atom_repo_el_gpgcheck }}"
    gpgkey: "{{ atom_gpg_key }}"
    repo_gpgcheck: "{{ atom_repo_el_repogpgcheck }}"
    file: "{{ atom_repo_el_filename }}"
    state: "{{ atom_repo_desired_state }}"
    enabled: "{{ atom_repo_el_enabled }}"

- name: EL Family | Installing {{ atom_app }}
  ansible.builtin.yum:
    name: "{{ atom_app }}"
    state: "{{ atom_desired_state }}"
    update_cache: yes
