---
# tasks file for atom - Debian

- name: Install python3-apt on Debian based systems, required for package_facts.
  apt:
    name: python3-apt
    state: present
    force_apt_get: yes
    update_cache: yes
- name: Install apt-transport-https on Debian based systems.
  apt:
    name: apt-transport-https
    state: present
    force_apt_get: yes
    update_cache: yes
  # when: packages['apt-transport-https'] is not defined
- name: Add gpg signing key for {{ atom_app  }}.
  apt_key:
    url: "{{ atom_gpg_key }}"
    state: present
- name: Adding repository {{ atom_repo_debian }} on Debian based systems.
  apt_repository:
    repo: "{{ atom_repo_debian }}"
    state: "{{ atom_repo_desired_state }}"
    filename: "{{ atom_repo_debian_filename }}"
    update_cache: yes
- name: Installing {{ atom_app }} on Debian based systems.
  apt:
    name: "{{ atom_app }}"
    state: "{{ atom_desired_state }}"
    force_apt_get: yes
    update_cache: yes
